---
model: Lykon/DreamShaper
width: 560
height: 960
batch_size: 25
phrases:
  context: portrait of the stunning sexy ginger-haired poison ivy, big breasts
  style:
    bio: bloom, blossoms, biophilic design, floral, biopunk, goth, in the art of batman
  base: masterpiece, perfect anatomy, 32k UHD resolution, best quality, highres, realistic photo, professional photography, cinematic angle, cinematic lights, brilliant, vibrant, vivid color, highest detailed, stunning composition, hyper emotional, cowboy shot
prompts:
  leaves:
    content: "{{ phrases.context }}, wearing sexy green leaves, {{ phrases.style.bio }}, {{ phrases.base }}"
  latex:
    content: "{{ phrases.context }}, wearing sexy green latex, {{ phrases.style.bio }}, {{ phrases.base }}"
  lingerie:
    content: "{{ phrases.context }}, wearing sexy purple lingerie, {{ phrases.style.bio }}, {{ phrases.base }}"
  dessous:
    content: "{{ phrases.context }}, wearing sexy green dessous, {{ phrases.style.bio }}, {{ phrases.base }}"
  mask:
    content: "{{ phrases.context }}, wearing only a sexy eye-mask, {{ phrases.style.bio }}, {{ phrases.base }}"