---
model: stablediffusionapi/majicmix-v7
width: 560
height: 960
batch_size: 25
phrases:
  context: portrait of a stunning sexy ginger-haired porn actress, big breasts
  base: dildo, masterpiece, perfect anatomy, 32k UHD resolution, best quality, highres, realistic photo, professional photography, cinematic angle, cinematic lights, brilliant, vibrant, vivid color, highest detailed, stunning composition, hyper emotional, cowboy shot
prompts:
  nun:
    content: "{{ phrases.context }}, dressed as nun, {{ phrases.base }}"
  nurse:
    content: "{{ phrases.context }}, dressed as nurse, {{ phrases.base }}"
  schoolgirl:
    content: "{{ phrases.context }}, dressed as schoolgirl, {{ phrases.base }}"
  maid:
    content: "{{ phrases.context }}, dressed as maid, {{ phrases.base }}"
  domina:
    content: "{{ phrases.context }}, dressed as domina, {{ phrases.base }}"
  teacher:
    content: "{{ phrases.context }}, dressed as teacher, {{ phrases.base }}"
  vampire:
    content: "{{ phrases.context }}, dressed as vampire, {{ phrases.base }}"
  punk:
    content: "{{ phrases.context }}, dressed as punk, {{ phrases.base }}"
  ballerina:
    content: "{{ phrases.context }}, dressed as ballerina, {{ phrases.base }}"
  geisha:
    content: "{{ phrases.context }}, dressed as geisha, {{ phrases.base }}"